// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

// Hardcoded values for troubleshooting GitHub Pages deployment
const SUPABASE_URL = 'https://jgjbdtzzuroglzzfluwz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnamJkdHp6dXJvZ2x6emZsdXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MjE5MTMsImV4cCI6MjA3Njk5NzkxM30.la8TvZWZs4xorSdmywNXolBIWNGEvTGKImCXvc0MEVw';

console.log('Supabase Configuration:', {
  url: SUPABASE_URL,
  keyPrefix: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...',
  environment: 'hardcoded-for-debugging'
});

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables');
}

if (!SUPABASE_URL.startsWith('https://')) {
  throw new Error('Invalid Supabase URL format');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});